server:
  port: 8081

mensaje: "InventarioService Micro"

spring:
  application:
    name: micro-usuario
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/dbinventario?useSSL=false&serverTimezone=UTC
    username: root
    password: mysql
